package com.fajing.model;

import com.fajing.model.base.BaseBasicFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicFile extends BaseBasicFile<BasicFile> {
	public static final BasicFile dao = new BasicFile().dao();
}
