package com.fajing.model;

import com.fajing.model.base.BaseErrorUrl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ErrorUrl extends BaseErrorUrl<ErrorUrl> {
	public static final ErrorUrl dao = new ErrorUrl().dao();
}
