package com.fajing.model;

import com.fajing.model.base.BaseParentFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ParentFile extends BaseParentFile<ParentFile> {
	public static final ParentFile dao = new ParentFile().dao();
}
