package com.fajing.model;

import com.fajing.model.base.BaseQueryCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QueryCity extends BaseQueryCity<QueryCity> {
	public static final QueryCity dao = new QueryCity().dao();
}
