package com.fajing.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBasicFile<M extends BaseBasicFile<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCreationTime(java.util.Date creationTime) {
		set("creation_time", creationTime);
		return (M)this;
	}
	
	public java.util.Date getCreationTime() {
		return get("creation_time");
	}

	public M setPid(java.lang.Long pid) {
		set("pid", pid);
		return (M)this;
	}
	
	public java.lang.Long getPid() {
		return getLong("pid");
	}

	public M setPname(java.lang.String pname) {
		set("pname", pname);
		return (M)this;
	}
	
	public java.lang.String getPname() {
		return getStr("pname");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setSequence(java.lang.String sequence) {
		set("sequence", sequence);
		return (M)this;
	}
	
	public java.lang.String getSequence() {
		return getStr("sequence");
	}

	public M setSequenceNumber(java.lang.Integer sequenceNumber) {
		set("sequence_number", sequenceNumber);
		return (M)this;
	}
	
	public java.lang.Integer getSequenceNumber() {
		return getInt("sequence_number");
	}

	public M setBasicStatic(java.lang.Integer basicStatic) {
		set("basic_static", basicStatic);
		return (M)this;
	}
	
	public java.lang.Integer getBasicStatic() {
		return getInt("basic_static");
	}

}
